[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.filesystem_size = 0.5m
monitor_speed = 115200
upload_protocol = esp-builtin
board_build.filesystem = littlefs

lib_deps =
    olikraus/U8g2@^2.35.19
    bblanchon/ArduinoJson@^7.2.0
    h2zero/NimBLE-Arduino@^1.4.2
